/**
 * Astro Generator Utilities for VectorForge
 * Generates production-ready .astro components, layouts, and asset snippets.
 */

export interface AstroComponentOptions {
  componentName?: string;
  includeProps?: boolean;
  responsiveSize?: boolean;
}

/**
 * Format string to PascalCase for valid Astro/React component naming
 */
export function toPascalCase(str: string): string {
  if (!str) return 'VectorIcon';
  return str
    .replace(/[^a-zA-Z0-9_-]/g, ' ')
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('') || 'VectorIcon';
}

/**
 * Convert an SVG string into an idiomatic, typed .astro component
 */
export function convertSvgToAstroComponent(
  svgString: string,
  options: AstroComponentOptions = {}
): string {
  const { includeProps = true } = options;

  let cleanedSvg = svgString
    .replace(/<\?xml[\s\S]*?\?>/gi, '')
    .replace(/<!DOCTYPE[\s\S]*?>/gi, '')
    .trim();

  // Find root <svg> opening tag
  const svgOpenMatch = cleanedSvg.match(/<svg([^>]*)>/i);
  if (!svgOpenMatch) {
    return cleanedSvg;
  }

  const rawAttributes = svgOpenMatch[1];
  let innerContent = cleanedSvg.substring(svgOpenMatch[0].length);
  // Remove closing </svg> tag for wrapping
  innerContent = innerContent.replace(/<\/svg>\s*$/i, '').trim();

  // Extract viewBox if present
  const viewBoxMatch = rawAttributes.match(/viewBox=["']([^"']+)["']/i);
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 512 512';

  // Extract existing width and height if any
  const widthMatch = rawAttributes.match(/\bwidth=["']([^"']+)["']/i);
  const heightMatch = rawAttributes.match(/\bheight=["']([^"']+)["']/i);
  const defaultWidth = widthMatch ? widthMatch[1] : '24';
  const defaultHeight = heightMatch ? heightMatch[1] : '24';

  // Clean attributes: remove width, height, class, and viewBox from rawAttributes to avoid duplication
  let remainingAttributes = rawAttributes
    .replace(/\b(width|height|viewBox|class)\s*=\s*["'][^"']*["']/gi, '')
    .trim();

  // Format Astro Component
  if (!includeProps) {
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="${defaultWidth}" height="${defaultHeight}" ${remainingAttributes}>
  ${innerContent}
</svg>`;
  }

  const astroTemplate = `---
/**
 * Generated by VectorForge for Astro
 * 100% Client-Side Vector Studio
 */
interface Props {
  size?: number | string;
  width?: number | string;
  height?: number | string;
  class?: string;
  [key: string]: any;
}

const {
  size,
  width = size ?? "${defaultWidth}",
  height = size ?? "${defaultHeight}",
  class: className,
  ...rest
} = Astro.props;
---

<svg
  xmlns="http://www.w3.org/2000/svg"
  viewBox="${viewBox}"
  width={width}
  height={height}
  class:list={[className]}
  {...rest}${remainingAttributes ? `\n  ${remainingAttributes}` : ''}
>
  ${innerContent}
</svg>
`;

  return astroTemplate.trim();
}

/**
 * Generate Astro Layout <head> snippet with favicon assets
 */
export function getAstroFaviconLayoutSnippet(themeColor = '#3b82f6'): string {
  return `---
// src/layouts/Layout.astro
// Tip: Drop generated favicon assets into your project's \`public/\` folder:
// - public/favicon.ico
// - public/favicon.svg
// - public/apple-touch-icon.png
// - public/site.webmanifest

interface Props {
  title?: string;
  description?: string;
}

const {
  title = 'My Astro Website',
  description = 'High-performance website built with Astro'
} = Astro.props;
---

<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{title}</title>
    <meta name="description" content={description} />

    <!-- Favicon & App Icons generated with VectorForge -->
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <link rel="icon" href="/favicon.ico" sizes="any" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="manifest" href="/site.webmanifest" />
    <meta name="theme-color" content="${themeColor}" />
  </head>
  <body>
    <slot />
  </body>
</html>`;
}

/**
 * Helper to download code string directly as an .astro file
 */
export function downloadAstroFile(content: string, filename = 'Icon.astro'): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.astro') ? filename : `${filename}.astro`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
