import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { renderSvgToBlob } from './canvas-renderer';
import { createIcoFromPngs } from './ico-encoder';

export interface FaviconPackOptions {
  appName?: string;
  shortName?: string;
  themeColor?: string;
  backgroundColor?: string;
}

export async function generateFaviconPack(
  svgContent: string,
  options: FaviconPackOptions = {}
): Promise<void> {
  const {
    appName = 'My Web Application',
    shortName = 'App',
    themeColor = '#3b82f6',
    backgroundColor = '#ffffff',
  } = options;

  const zip = new JSZip();

  // 1. Render required raster sizes
  const [blob16, blob32, blob48, blob180, blob192, blob512] = await Promise.all([
    renderSvgToBlob(svgContent, { width: 16, height: 16 }),
    renderSvgToBlob(svgContent, { width: 32, height: 32 }),
    renderSvgToBlob(svgContent, { width: 48, height: 48 }),
    renderSvgToBlob(svgContent, { width: 180, height: 180 }),
    renderSvgToBlob(svgContent, { width: 192, height: 192 }),
    renderSvgToBlob(svgContent, { width: 512, height: 512 }),
  ]);

  // 2. Generate multi-resolution favicon.ico (16, 32, 48)
  const icoBlob = await createIcoFromPngs([
    { pngBlob: blob16, size: 16 },
    { pngBlob: blob32, size: 32 },
    { pngBlob: blob48, size: 48 },
  ]);

  // 3. Add files to ZIP
  zip.file('favicon.ico', icoBlob);
  zip.file('favicon.svg', svgContent);
  zip.file('favicon-16x16.png', blob16);
  zip.file('favicon-32x32.png', blob32);
  zip.file('apple-touch-icon.png', blob180);
  zip.file('android-chrome-192x192.png', blob192);
  zip.file('android-chrome-512x512.png', blob512);

  // 4. Generate site.webmanifest
  const webmanifest = {
    name: appName,
    short_name: shortName,
    icons: [
      {
        src: '/android-chrome-192x192.png',
        sizes: '192x192',
        type: 'image/png',
      },
      {
        src: '/android-chrome-512x512.png',
        sizes: '512x512',
        type: 'image/png',
      },
    ],
    theme_color: themeColor,
    background_color: backgroundColor,
    display: 'standalone',
  };
  zip.file('site.webmanifest', JSON.stringify(webmanifest, null, 2));

  // 5. Generate README.txt with HTML head snippet
  const headSnippet = `<!-- Favicon & App Icon Tags generated by VectorForge -->
<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
<meta name="theme-color" content="${themeColor}">`;

  const readme = `VectorForge Favicon Pack
========================

How to install:
1. Extract all files into the root directory of your website (e.g. /public or your web root).
2. Insert the following HTML code into the <head> section of all your web pages:

${headSnippet}

Generated with VectorForge (100% Client-Side Favicon Studio).
`;

  zip.file('README.txt', readme);

  // 6. Generate ZIP and trigger download
  const content = await zip.generateAsync({ type: 'blob' });
  saveAs(content, 'favicon-pack.zip');
}

export function getHtmlHeadSnippet(themeColor = '#3b82f6'): string {
  return `<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
<meta name="theme-color" content="${themeColor}">`;
}
